version: '3.1'

services:
  #db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paybooc
      POSTGRES_DB: project
    container_name: db
    #volumes:
      #- ./postgresql/:/var/lib/postgresql/data/
    networks:
      - sb-db-ra
    expose:
      - 5112
    ports:
      - 5112:5432

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks:
      - sb-db-ra
    ports:
      - 8080:8080 

  #프론트앤드
  frontend:
    image: frontend
    working_dir: /frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - sb-db-ra
    ports: 
      - 3200:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  #백엔드 
  backend:
    image: backend
    working_dir: /backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - sb-db-ra
    ports: 
      - 8081:8080
    command: [“./gradlew”]
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/project
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=paybooc

networks:
  sb-db-ra: