spring:
  # PostgreSQL DB 설정
  #datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://db:5113/project
    #username: postgres
    #password: paybooc


 # Mybatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true   